options:
  formatter: stylish
  merge-default-rules: false
files:
  include: 'src/scss/**/*.scss'
  ignore:
    - 'node_modules/**/*.scss'
    - './src/scss/helpers'
rules:
  attribute-quotes:
    include: true
  hex-length:
    - 2
    - style: 'short'
  hex-notation:
    - 2
    - style: lowercase
  indentation:
    size: 2
  space-after-comma:
    include: true
  bem-depth: 1
  border-zero:
    - 1
    - convention: zero
  brace-style:
    - 2
    - allow-single-line: false
  class-name-format:
    - convention: 'hyphenatedlowercase'
    - allow-leading-underscore: false
  extends-before-declarations: 0
  extends-before-mixins: 0
  function-name-format: 1
  id-name-format:
    - convention: 'hyphenatedlowercase'
  leading-zero: 2
  mixin-name-format: 2
  mixins-before-declarations: 0
  no-extends: 2
  no-qualifying-elements: 0
  placeholder-name-format:
    - 2
    - allow-leading-underscore: false
    - convention: 'hyphenatedlowercase'
  property-sort-order: 0
  quotes:
    - 2
    - style: single
  variable-name-format:
    - allow-leading-underscore: false
    - convention: 'hyphenatedlowercase'
  force-pseudo-nesting: 2
